FROM node:22-alpine

WORKDIR /app

# Copiar apenas o necessário para instalar dependências
COPY package*.json ./

RUN npm install --legacy-peer-deps

# Copiar o resto do código
COPY . .

# Expor a porta do Storybook
EXPOSE 6006

# Comando para rodar o Storybook
CMD ["npm", "run", "storybook", "--", "--no-open", "--host", "0.0.0.0", "--port", "6006"]