"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-@d+p5#6r(**lr=fgui6ah_^tt!*3u)$jo!=9y)2w+^1wl)vyjm',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes', 'on')

ALLOWED_HOSTS = [
    host.strip() for host in os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,backend').split(',') if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'users',
    'finance',
    'monitoring',
    "corsheaders",
    "apps.core",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'monitoring.middleware.FinancialApiObservabilityMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

database_backend = os.getenv('DJANGO_DATABASE', 'sqlite').lower()
postgres_db = os.getenv('POSTGRES_DB')
postgres_user = os.getenv('POSTGRES_USER')
postgres_password = os.getenv('POSTGRES_PASSWORD')
postgres_host = os.getenv('POSTGRES_HOST')
postgres_port = os.getenv('POSTGRES_PORT')

if database_backend == 'postgres':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': postgres_db or 'projeto1',
            'USER': postgres_user or 'postgres',
            'PASSWORD': postgres_password or 'postgres',
            'HOST': postgres_host or '127.0.0.1',
            'PORT': postgres_port or '5432',
            'CONN_MAX_AGE': int(os.getenv('POSTGRES_CONN_MAX_AGE', '60')),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [

"http://localhost:5173",

]

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


def _env_bool(name: str, default: bool) -> bool:
    return os.getenv(name, str(default)).lower() in ('1', 'true', 'yes', 'on')


def _build_dashboard_cache_config() -> dict:
    backend = os.getenv('FINANCIAL_DASHBOARD_CACHE_BACKEND', 'locmem').lower()

    if backend == 'redis':
        return {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': os.getenv('FINANCIAL_DASHBOARD_CACHE_LOCATION', 'redis://redis:6379/1'),
            'TIMEOUT': int(os.getenv('FINANCIAL_DASHBOARD_CACHE_TTL_SECONDS', '30')),
            'KEY_PREFIX': os.getenv('FINANCIAL_DASHBOARD_CACHE_KEY_PREFIX', 'cony:financial-dashboard'),
        }

    if backend == 'memcached':
        return {
            'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
            'LOCATION': os.getenv('FINANCIAL_DASHBOARD_CACHE_LOCATION', 'memcached:11211'),
            'TIMEOUT': int(os.getenv('FINANCIAL_DASHBOARD_CACHE_TTL_SECONDS', '30')),
            'KEY_PREFIX': os.getenv('FINANCIAL_DASHBOARD_CACHE_KEY_PREFIX', 'cony:financial-dashboard'),
        }

    return {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': os.getenv('FINANCIAL_DASHBOARD_CACHE_LOCATION', 'cony-financial-dashboard'),
        'TIMEOUT': int(os.getenv('FINANCIAL_DASHBOARD_CACHE_TTL_SECONDS', '30')),
        'KEY_PREFIX': os.getenv('FINANCIAL_DASHBOARD_CACHE_KEY_PREFIX', 'cony:financial-dashboard'),
    }


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'default-cache',
    },
    'financial_dashboard': _build_dashboard_cache_config(),
}


FINANCIAL_API_ENABLE_SIMULATED_DELAY = _env_bool('FINANCIAL_API_ENABLE_SIMULATED_DELAY', True)
FINANCIAL_API_MAX_SIMULATED_DELAY_MS = int(os.getenv('FINANCIAL_API_MAX_SIMULATED_DELAY_MS', '3000'))
FINANCIAL_API_ALERT_THRESHOLD_MS = int(os.getenv('FINANCIAL_API_ALERT_THRESHOLD_MS', '800'))
FINANCIAL_QUERY_SLOW_THRESHOLD_MS = int(os.getenv('FINANCIAL_QUERY_SLOW_THRESHOLD_MS', '120'))
FINANCIAL_QUERY_TARGET_AVG_MS = int(os.getenv('FINANCIAL_QUERY_TARGET_AVG_MS', '150'))
FINANCIAL_QUERY_TARGET_P95_MS = int(os.getenv('FINANCIAL_QUERY_TARGET_P95_MS', '300'))
FINANCIAL_QUERY_TARGET_SLOW_PERCENT = float(os.getenv('FINANCIAL_QUERY_TARGET_SLOW_PERCENT', '5'))
FINANCIAL_QUERY_INDEX_USAGE_PERCENT = float(os.getenv('FINANCIAL_QUERY_INDEX_USAGE_PERCENT', '90'))
FINANCIAL_QUERY_TARGET_INDEX_USAGE_PERCENT = float(os.getenv('FINANCIAL_QUERY_TARGET_INDEX_USAGE_PERCENT', '90'))
FINANCIAL_QUERY_RESOURCE_CPU_PERCENT = float(os.getenv('FINANCIAL_QUERY_RESOURCE_CPU_PERCENT', '0'))
FINANCIAL_QUERY_TARGET_CPU_PERCENT = float(os.getenv('FINANCIAL_QUERY_TARGET_CPU_PERCENT', '80'))
FINANCIAL_QUERY_RESOURCE_MEMORY_MB = float(os.getenv('FINANCIAL_QUERY_RESOURCE_MEMORY_MB', '0'))
FINANCIAL_QUERY_TARGET_MEMORY_MB = float(os.getenv('FINANCIAL_QUERY_TARGET_MEMORY_MB', '1024'))
FINANCIAL_DASHBOARD_TARGET_LOAD_MS = int(os.getenv('FINANCIAL_DASHBOARD_TARGET_LOAD_MS', '400'))
FINANCIAL_DASHBOARD_TARGET_CHART_MS = int(os.getenv('FINANCIAL_DASHBOARD_TARGET_CHART_MS', '500'))
FINANCIAL_DASHBOARD_TARGET_FILTER_MS = int(os.getenv('FINANCIAL_DASHBOARD_TARGET_FILTER_MS', '350'))
FINANCIAL_DASHBOARD_TARGET_EXPORT_MS = int(os.getenv('FINANCIAL_DASHBOARD_TARGET_EXPORT_MS', '1200'))
FINANCIAL_DASHBOARD_CACHE_ENABLED = _env_bool('FINANCIAL_DASHBOARD_CACHE_ENABLED', True)
FINANCIAL_DASHBOARD_CACHE_TTL_SECONDS = int(os.getenv('FINANCIAL_DASHBOARD_CACHE_TTL_SECONDS', '30'))
FINANCIAL_DASHBOARD_CACHE_INVALIDATE_ON_WRITE = _env_bool('FINANCIAL_DASHBOARD_CACHE_INVALIDATE_ON_WRITE', True)
FINANCIAL_DASHBOARD_CACHE_KEY = os.getenv('FINANCIAL_DASHBOARD_CACHE_KEY', 'snapshot')
