# Generated by Django 4.2.30 on 2026-07-17 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_costureira_capacidade_base_semanal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('numero_parcela', models.PositiveIntegerField(default=1)),
                ('total_parcelas', models.PositiveIntegerField(default=1)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='users.servico')),
            ],
            options={
                'ordering': ['data_vencimento'],
                'indexes': [models.Index(fields=['status'], name='finance_pag_status_3ec892_idx'), models.Index(fields=['data_vencimento'], name='finance_pag_data_ve_c08694_idx'), models.Index(fields=['servico', 'status'], name='finance_pag_servico_9100e7_idx')],
            },
        ),
    ]
