# Generated by Django 4.2.30 on 2026-07-19 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='numero_parcela',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='total_parcelas',
        ),
    ]
