# Generated by Django 4.2.30 on 2026-07-28 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_costureira_capacidade_base_semanal_and_more'),
        ('finance', '0002_remove_pagamento_numero_parcela_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamento',
            options={'ordering': ['data_entrega']},
        ),
        migrations.RemoveIndex(
            model_name='pagamento',
            name='finance_pag_data_ve_c08694_idx',
        ),
        migrations.RenameField(
            model_name='pagamento',
            old_name='data_vencimento',
            new_name='data_entrega',
        ),
        migrations.RenameField(
            model_name='pagamento',
            old_name='criado_em',
            new_name='enviado_em',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='observacoes',
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='users.servico'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['data_entrega'], name='finance_pag_data_en_aa0449_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagamento',
            constraint=models.CheckConstraint(check=models.Q(('valor__gt', 0)), name='pagamento_valor_maior_que_zero'),
        ),
    ]
