# Generated by Django 4.2.30 on 2026-07-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_alter_pagamento_options_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="pagamento",
            new_name="idx_pagamento_status",
            old_name="finance_pag_status_3ec892_idx",
        ),
        migrations.RenameIndex(
            model_name="pagamento",
            new_name="idx_pagamento_data_entrega",
            old_name="finance_pag_data_en_aa0449_idx",
        ),
        migrations.RenameIndex(
            model_name="pagamento",
            new_name="idx_pagamento_servico_status",
            old_name="finance_pag_servico_9100e7_idx",
        ),
        migrations.AddIndex(
            model_name="pagamento",
            index=models.Index(fields=["servico_id"], name="idx_pagamento_servico"),
        ),
        migrations.AddIndex(
            model_name="pagamento",
            index=models.Index(
                fields=["status", "data_entrega"], name="idx_pagamento_status_data"
            ),
        ),
        migrations.AddIndex(
            model_name="pagamento",
            index=models.Index(
                fields=["data_pagamento"], name="idx_pagamento_data_pagamento"
            ),
        ),
    ]
