# Generated by Django 6.0.6 on 2026-07-03 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.TextField()),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Costureira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('contato', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo_servico_preferido', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Capacidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField()),
                ('semana_fim', models.DateField()),
                ('quantidade_aberto', models.IntegerField()),
                ('indice_complexidade', models.IntegerField()),
                ('costureira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacidades', to='users.costureira')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50)),
                ('producao_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pecas_produzidas', models.IntegerField()),
                ('servicos_atraso', models.IntegerField(default=0)),
                ('servicos_aberto', models.IntegerField(default=0)),
                ('costureira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='users.costureira')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('complexidade', models.IntegerField(default=0)),
                ('data_envio', models.DateField()),
                ('prazo_entrega', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacoes', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_cliente', to='users.cliente')),
                ('costureira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_costureira', to='users.costureira')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_produto', to='users.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Financeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=100)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pendente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_pagamento', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('costureira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financeiros', to='users.costureira')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financeiros', to='users.servico')),
            ],
        ),
    ]
