# Generated by Django 6.0.6 on 2026-07-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='prazo_entrega',
            field=models.DateField(),
        ),
    ]
