# Generated by Django 4.2.30 on 2026-07-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costureira',
            name='capacidade_base_semanal',
            field=models.PositiveIntegerField(default=5, help_text='Quantos dias úteis de trabalho ela tem numa semana cheia.'),
        ),
        migrations.AddField(
            model_name='costureira',
            name='disponibilidade_percentual',
            field=models.PositiveIntegerField(default=100, help_text='De 0 a 100, o quão livre ela está agora pra receber novos pedidos.'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo_produto',
            field=models.CharField(blank=True, choices=[('ILHO', 'Cortina de Ilhó'), ('PREGA_MACHO', 'Cortina de Prega Macho'), ('FORRO', 'Forro'), ('BLACKOUT', 'Blackout'), ('ALMOFADA', 'Almofada')], help_text='Categoria do produto, usada no cálculo de complexidade.', max_length=20),
        ),
        migrations.AddField(
            model_name='servico',
            name='tamanho',
            field=models.CharField(blank=True, choices=[('P', 'Pequena'), ('M', 'Média'), ('G', 'Grande'), ('ESP', 'Especial / Pé direito duplo')], help_text='Tamanho considerado pra todas as peças deste serviço (por enquanto).', max_length=3),
        ),
    ]
