# Generated by Django 4.2.30 on 2026-07-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_costureira_capacidade_base_semanal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='complexidade_manual',
            field=models.BooleanField(default=False, help_text='Se marcado, o sistema NAO recalcula a complexidade automaticamente - fica sob controle da gestora.'),
        ),
    ]
