# Generated by Django 4.2.30 on 2026-07-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_costureira_capacidade_base_semanal_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='costureira',
            index=models.Index(fields=['ativo'], name='idx_costureira_ativo'),
        ),
        migrations.AddIndex(
            model_name='costureira',
            index=models.Index(fields=['tipo_servico_preferido'], name='idx_costureira_tipo'),
        ),
        migrations.AddIndex(
            model_name='servico',
            index=models.Index(fields=['costureira', 'data_envio'], name='idx_serv_cost_data'),
        ),
        migrations.AddIndex(
            model_name='servico',
            index=models.Index(fields=['cliente', 'data_envio'], name='idx_serv_cli_data'),
        ),
        migrations.AddIndex(
            model_name='servico',
            index=models.Index(fields=['prazo_entrega'], name='idx_serv_prazo'),
        ),
        migrations.AddIndex(
            model_name='servico',
            index=models.Index(fields=['valor'], name='idx_serv_valor'),
        ),
        migrations.AddIndex(
            model_name='servico',
            index=models.Index(fields=['complexidade'], name='idx_serv_complex'),
        ),
    ]
