# Generated by Django 4.2.30 on 2026-07-22 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_financial_query_indexes'),
        ('users', '0003_servico_complexidade_manual'),
    ]

    operations = [
    ]
