# Generated by Django 4.2.30 on 2026-07-30 01:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_financial_query_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="costureira",
            name="idx_costureira_ativo",
        ),
        migrations.RemoveIndex(
            model_name="costureira",
            name="idx_costureira_tipo",
        ),
        migrations.RemoveIndex(
            model_name="servico",
            name="idx_serv_cost_data",
        ),
        migrations.RemoveIndex(
            model_name="servico",
            name="idx_serv_cli_data",
        ),
        migrations.RemoveIndex(
            model_name="servico",
            name="idx_serv_prazo",
        ),
        migrations.RemoveIndex(
            model_name="servico",
            name="idx_serv_valor",
        ),
        migrations.RemoveIndex(
            model_name="servico",
            name="idx_serv_complex",
        ),
        migrations.AddField(
            model_name="servico",
            name="criacao",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Data de Criação",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="servico",
            name="data_envio",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="servico",
            name="prazo_entrega",
            field=models.DateField(),
        ),
    ]
