# Generated by Django 4.2.30 on 2026-07-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_costureira_idx_costureira_ativo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servico",
            name="criacao",
        ),
        migrations.AlterField(
            model_name="servico",
            name="data_envio",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="servico",
            name="prazo_entrega",
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name="costureira",
            index=models.Index(fields=["ativo"], name="idx_costureira_ativo"),
        ),
        migrations.AddIndex(
            model_name="costureira",
            index=models.Index(
                fields=["tipo_servico_preferido"], name="idx_costureira_tipo"
            ),
        ),
        migrations.AddIndex(
            model_name="servico",
            index=models.Index(
                fields=["costureira", "data_envio"], name="idx_serv_cost_data"
            ),
        ),
        migrations.AddIndex(
            model_name="servico",
            index=models.Index(
                fields=["cliente", "data_envio"], name="idx_serv_cli_data"
            ),
        ),
        migrations.AddIndex(
            model_name="servico",
            index=models.Index(fields=["prazo_entrega"], name="idx_serv_prazo"),
        ),
        migrations.AddIndex(
            model_name="servico",
            index=models.Index(fields=["valor"], name="idx_serv_valor"),
        ),
        migrations.AddIndex(
            model_name="servico",
            index=models.Index(fields=["complexidade"], name="idx_serv_complex"),
        ),
    ]
