# Generated by Django 4.2.30 on 2026-07-28 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_merge_20260721_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIACAO', 'Criação'), ('ATUALIZACAO', 'Atualização'), ('EXCLUSAO', 'Exclusão')], max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('objeto_id', models.CharField(max_length=50)),
                ('campo_alterado', models.CharField(max_length=100)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_novo', models.TextField(blank=True, null=True)),
                ('justificativa', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoIndisponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FERIAS', 'Férias'), ('AFASTAMENTO_MEDICO', 'Afastamento médico'), ('LICENCA', 'Licença'), ('OUTRO', 'Outro')], max_length=30)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('costureira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_indisponibilidade', to='users.costureira')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_inicio'],
                'indexes': [models.Index(fields=['costureira', 'data_inicio', 'data_fim'], name='users_perio_costure_a69f83_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='periodoindisponibilidade',
            constraint=models.CheckConstraint(check=models.Q(('data_fim__gte', models.F('data_inicio'))), name='periodo_data_fim_apos_inicio'),
        ),
    ]
