# Generated by Django 4.2.30 on 2026-07-30 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_logauditoria_periodoindisponibilidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatorio',
            options={'ordering': ['-periodo']},
        ),
        migrations.AddField(
            model_name='relatorio',
            name='gerado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='costureira',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco para o relatório geral consolidado do período.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='users.costureira'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='periodo',
            field=models.CharField(help_text='Formato AAAA-MM, ex: 2026-07', max_length=50),
        ),
        migrations.AddIndex(
            model_name='relatorio',
            index=models.Index(fields=['periodo'], name='idx_relatorio_periodo'),
        ),
    ]
