# Generated by Django 4.2.30 on 2026-07-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_logauditoria_periodoindisponibilidade_and_more"),
        ("users", "0005_remove_servico_criacao_alter_servico_data_envio_and_more"),
    ]

    operations = []
