# Generated by Django 4.2.30 on 2026-07-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_relatorio_options_relatorio_gerado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='detalhamento_por_costureira',
            field=models.JSONField(blank=True, default=list, help_text='Produção de cada costureira no período (id, nome, valor, peças, atrasos, abertos).'),
        ),
    ]
