# Generated by Django 4.2.30 on 2026-07-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_merge_20260730_1545"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="servico",
            name="idx_serv_prazo",
        ),
        migrations.RemoveIndex(
            model_name="servico",
            name="idx_serv_complex",
        ),
        migrations.RenameIndex(
            model_name="servico",
            new_name="idx_servico_cliente_data",
            old_name="idx_serv_cli_data",
        ),
        migrations.RenameIndex(
            model_name="servico",
            new_name="idx_servico_costureira_data",
            old_name="idx_serv_cost_data",
        ),
        migrations.RenameIndex(
            model_name="servico",
            new_name="idx_servico_valor",
            old_name="idx_serv_valor",
        ),
        migrations.AddIndex(
            model_name="servico",
            index=models.Index(
                fields=["data_envio", "prazo_entrega"], name="idx_servico_data_prazo"
            ),
        ),
        migrations.AddIndex(
            model_name="servico",
            index=models.Index(fields=["data_envio"], name="idx_servico_data_envio"),
        ),
    ]
