# Generated by Django 4.2.30 on 2026-07-31 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_relatorio_detalhamento_por_costureira'),
        ('users', '0007_remove_servico_idx_serv_prazo_and_more'),
    ]

    operations = [
    ]
